package DUJS.main;

import DUJS.design.venDetailsPage;
import DUJS.methods.DataMethods;
import DUJS.methods.ImageMethods;
import DUJS.methods.conn;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

public class appMain extends javax.swing.JFrame {
        String VuserName,userid,nCity;
        String type = "NormalUser";
        Color SecCol = new Color(39,57,81);
        Color DeSecCol = new Color(24,17,68);
        DataMethods dm = new DataMethods();
        conn c = new conn();
        ImageMethods im = new ImageMethods();
        JLabel l;
        
    public appMain(String userid) {
        initComponents();
        try{
            this.userid = userid;
            this.Dash2.setVisible(false);
            this.Dash1.setVisible(true);
            Statement s = c.connect.createStatement();
            String sql = "select * from login where userid = '"+userid+"'";
            ResultSet rs = s.executeQuery(sql);
            
            while(rs.next()){
                 VuserName = rs.getString("username");
                 lUserName.setText(VuserName);
                 imgLabel.setIcon(im.getImage(imgLabel, userid));
                 hSubPan1.revalidate();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        JTableHeader tbh = venTable.getTableHeader();
        tbh.setBackground(DeSecCol);
        tbh.setFont(new Font("SansSerif",1,18));
        
        lPlumber.setIcon(im.reSize("src/DUJS/Images/plumber.jpg", lPlumber));
        lCarpenter.setIcon(im.reSize("src/DUJS/Images/carpenter.jpg", lCarpenter));
        lCarWashing.setIcon(im.reSize("src/DUJS/Images/carwash.jpg", lCarWashing));
        lPainter.setIcon(im.reSize("src/DUJS/Images/painter.jpg", lPainter));
        lHClean.setIcon(im.reSize("src/DUJS/Images/houseC.jpg", lHClean));
        lElect.setIcon(im.reSize("src/DUJS/Images/electrician.jpg", lElect));
        lBarber.setIcon(im.reSize("src/DUJS/Images/barber.jpg", lBarber));
        lTechni.setIcon(im.reSize("src/DUJS/Images/technician.jpg", lTechni));
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNoti = new javax.swing.JDialog();
        notiPanM = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        menuPan = new javax.swing.JPanel();
        mSubPan1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnDash = new javax.swing.JLabel();
        mSubPan3 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAccDel = new javax.swing.JLabel();
        headPan = new javax.swing.JPanel();
        hSubPan1 = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lUserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mainPan = new javax.swing.JPanel();
        panDash = new javax.swing.JPanel();
        Dash1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PanPlumber = new javax.swing.JPanel();
        lPlumber = new javax.swing.JLabel();
        btnFindPlum = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnFindPaint = new javax.swing.JButton();
        lPainter = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lTechni = new javax.swing.JLabel();
        btnFindTech = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lElect = new javax.swing.JLabel();
        btnFindElec = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lBarber = new javax.swing.JLabel();
        btnFindBarb = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lHClean = new javax.swing.JLabel();
        btnFindHCle = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        lCarWashing = new javax.swing.JLabel();
        btnFindCarCl = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        lCarpenter = new javax.swing.JLabel();
        btnFindCarp = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Dash2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        venTable = new javax.swing.JTable();
        btnrRefR = new javax.swing.JLabel();
        panAccDel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sbAccDel = new javax.swing.JScrollBar();
        jLabel11 = new javax.swing.JLabel();
        tfMobNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfEmailId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAdd = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        btnSaChang = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        tfUName = new javax.swing.JTextField();
        btnEdit1 = new javax.swing.JButton();
        btnEdit2 = new javax.swing.JButton();
        btnEdit3 = new javax.swing.JButton();
        btnEdit4 = new javax.swing.JButton();

        panNoti.setBackground(new java.awt.Color(255, 255, 255));
        panNoti.setUndecorated(true);
        panNoti.setResizable(false);

        notiPanM.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout notiPanMLayout = new javax.swing.GroupLayout(notiPanM);
        notiPanM.setLayout(notiPanMLayout);
        notiPanMLayout.setHorizontalGroup(
            notiPanMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        notiPanMLayout.setVerticalGroup(
            notiPanMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panNotiLayout = new javax.swing.GroupLayout(panNoti.getContentPane());
        panNoti.getContentPane().setLayout(panNotiLayout);
        panNotiLayout.setHorizontalGroup(
            panNotiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notiPanM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panNotiLayout.setVerticalGroup(
            panNotiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notiPanM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        menuPan.setBackground(new java.awt.Color(24, 17, 68));

        mSubPan1.setBackground(new java.awt.Color(39, 57, 81));
        mSubPan1.setPreferredSize(new java.awt.Dimension(149, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        btnDash.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDash.setForeground(new java.awt.Color(255, 255, 255));
        btnDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDash.setText("Dashboard");
        btnDash.setPreferredSize(new java.awt.Dimension(41, 20));
        btnDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mSubPan1Layout = new javax.swing.GroupLayout(mSubPan1);
        mSubPan1.setLayout(mSubPan1Layout);
        mSubPan1Layout.setHorizontalGroup(
            mSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mSubPan1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        mSubPan1Layout.setVerticalGroup(
            mSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mSubPan1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mSubPan3.setBackground(new java.awt.Color(24, 17, 68));
        mSubPan3.setPreferredSize(new java.awt.Dimension(0, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        btnAccDel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnAccDel.setForeground(new java.awt.Color(255, 255, 255));
        btnAccDel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAccDel.setText("Account Details");
        btnAccDel.setPreferredSize(new java.awt.Dimension(41, 20));
        btnAccDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAccDelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mSubPan3Layout = new javax.swing.GroupLayout(mSubPan3);
        mSubPan3.setLayout(mSubPan3Layout);
        mSubPan3Layout.setHorizontalGroup(
            mSubPan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mSubPan3Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mSubPan3Layout.setVerticalGroup(
            mSubPan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mSubPan3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAccDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout menuPanLayout = new javax.swing.GroupLayout(menuPan);
        menuPan.setLayout(menuPanLayout);
        menuPanLayout.setHorizontalGroup(
            menuPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mSubPan1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(mSubPan3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        menuPanLayout.setVerticalGroup(
            menuPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(mSubPan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mSubPan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headPan.setBackground(new java.awt.Color(204, 255, 255));
        headPan.setPreferredSize(new java.awt.Dimension(1210, 80));

        hSubPan1.setBackground(new java.awt.Color(255, 255, 255));

        imgLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Name :");

        lUserName.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>|<br>|<br>|<br>|<br></html>");

        javax.swing.GroupLayout hSubPan1Layout = new javax.swing.GroupLayout(hSubPan1);
        hSubPan1.setLayout(hSubPan1Layout);
        hSubPan1Layout.setHorizontalGroup(
            hSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hSubPan1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(hSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        hSubPan1Layout.setVerticalGroup(
            hSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hSubPan1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(hSubPan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hSubPan1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_Logout_41px.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });

        tfSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchKeyPressed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_search_30px.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("<html>Explore :</html>");

        javax.swing.GroupLayout headPanLayout = new javax.swing.GroupLayout(headPan);
        headPan.setLayout(headPanLayout);
        headPanLayout.setHorizontalGroup(
            headPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headPanLayout.createSequentialGroup()
                .addComponent(btnLogOut)
                .addGap(236, 236, 236)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hSubPan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headPanLayout.setVerticalGroup(
            headPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hSubPan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headPanLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(headPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPan.setLayout(new java.awt.CardLayout());

        panDash.setBackground(new java.awt.Color(255, 255, 255));
        panDash.setLayout(new java.awt.CardLayout());

        Dash1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setText("Dashboard");

        jLabel7.setText("________________________________________________________________________________________________________________________________________________________________________");

        btnFindPlum.setBackground(new java.awt.Color(24, 17, 68));
        btnFindPlum.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnFindPlum.setForeground(new java.awt.Color(255, 255, 255));
        btnFindPlum.setText("Find Plumber Now");
        btnFindPlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPlumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanPlumberLayout = new javax.swing.GroupLayout(PanPlumber);
        PanPlumber.setLayout(PanPlumberLayout);
        PanPlumberLayout.setHorizontalGroup(
            PanPlumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lPlumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanPlumberLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFindPlum, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanPlumberLayout.setVerticalGroup(
            PanPlumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanPlumberLayout.createSequentialGroup()
                .addComponent(lPlumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFindPlum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnFindPaint.setBackground(new java.awt.Color(24, 17, 68));
        btnFindPaint.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnFindPaint.setForeground(new java.awt.Color(255, 255, 255));
        btnFindPaint.setText("Find Painter Now");
        btnFindPaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFindPaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lPainter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(lPainter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFindPaint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnFindTech.setBackground(new java.awt.Color(24, 17, 68));
        btnFindTech.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnFindTech.setForeground(new java.awt.Color(255, 255, 255));
        btnFindTech.setText("Find Technicians");
        btnFindTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindTechActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTechni, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(btnFindTech, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lTechni, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFindTech))
        );

        btnFindElec.setBackground(new java.awt.Color(24, 17, 68));
        btnFindElec.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnFindElec.setForeground(new java.awt.Color(255, 255, 255));
        btnFindElec.setText("Find Electrcians");
        btnFindElec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindElecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lElect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFindElec, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lElect, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFindElec))
        );

        btnFindBarb.setBackground(new java.awt.Color(24, 17, 68));
        btnFindBarb.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnFindBarb.setForeground(new java.awt.Color(255, 255, 255));
        btnFindBarb.setText("Find Barber");
        btnFindBarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindBarbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lBarber, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(btnFindBarb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(lBarber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFindBarb))
        );

        btnFindHCle.setBackground(new java.awt.Color(24, 17, 68));
        btnFindHCle.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnFindHCle.setForeground(new java.awt.Color(255, 255, 255));
        btnFindHCle.setText("Find House Cleaners");
        btnFindHCle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindHCleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lHClean, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(btnFindHCle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lHClean, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFindHCle))
        );

        btnFindCarCl.setBackground(new java.awt.Color(24, 17, 68));
        btnFindCarCl.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnFindCarCl.setForeground(new java.awt.Color(255, 255, 255));
        btnFindCarCl.setText("FInd Car Cleaners");
        btnFindCarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCarClActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lCarWashing, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(btnFindCarCl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(lCarWashing, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFindCarCl))
        );

        btnFindCarp.setBackground(new java.awt.Color(24, 17, 68));
        btnFindCarp.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnFindCarp.setForeground(new java.awt.Color(255, 255, 255));
        btnFindCarp.setText("Find Carpenter");
        btnFindCarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCarpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lCarpenter, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(btnFindCarp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(lCarpenter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFindCarp))
        );

        jButton2.setBackground(new java.awt.Color(24, 17, 68));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Explore More..");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dash1Layout = new javax.swing.GroupLayout(Dash1);
        Dash1.setLayout(Dash1Layout);
        Dash1Layout.setHorizontalGroup(
            Dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Dash1Layout.createSequentialGroup()
                .addGroup(Dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dash1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6))
                    .addGroup(Dash1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(Dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Dash1Layout.createSequentialGroup()
                                .addGroup(Dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Dash1Layout.createSequentialGroup()
                                        .addComponent(PanPlumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(119, 119, 119)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Dash1Layout.createSequentialGroup()
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(119, 119, 119)
                                .addGroup(Dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Dash1Layout.createSequentialGroup()
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dash1Layout.setVerticalGroup(
            Dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dash1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(Dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanPlumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addGroup(Dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        panDash.add(Dash1, "card4");

        Dash2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setText("Dashboard");

        jLabel10.setText("________________________________________________________________________________________________________________________________________________________________________");

        venTable.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        venTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "City", "Years of Experience ", "Mobile No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        venTable.setOpaque(false);
        venTable.setRowHeight(30);
        venTable.getTableHeader().setResizingAllowed(false);
        venTable.getTableHeader().setReorderingAllowed(false);
        venTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(venTable);
        if (venTable.getColumnModel().getColumnCount() > 0) {
            venTable.getColumnModel().getColumn(0).setResizable(false);
            venTable.getColumnModel().getColumn(1).setResizable(false);
            venTable.getColumnModel().getColumn(2).setResizable(false);
            venTable.getColumnModel().getColumn(3).setResizable(false);
        }

        btnrRefR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_refresh_45px_1.png"))); // NOI18N
        btnrRefR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrRefRMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Dash2Layout = new javax.swing.GroupLayout(Dash2);
        Dash2.setLayout(Dash2Layout);
        Dash2Layout.setHorizontalGroup(
            Dash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Dash2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnrRefR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dash2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        Dash2Layout.setVerticalGroup(
            Dash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dash2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrRefR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        panDash.add(Dash2, "card3");

        mainPan.add(panDash, "card2");

        panAccDel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Account Details :");

        jLabel5.setText("________________________________________________________________________________________________________________________________________________________________________");

        sbAccDel.setBackground(new java.awt.Color(51, 51, 255));
        sbAccDel.setForeground(new java.awt.Color(255, 0, 153));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setText("Mobile No. :");

        tfMobNo.setBackground(new java.awt.Color(226, 226, 226));
        tfMobNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfMobNo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("Email Id :");

        tfEmailId.setBackground(new java.awt.Color(226, 226, 226));
        tfEmailId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfEmailId.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setText("Residential  Address :");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tfAdd.setBackground(new java.awt.Color(226, 226, 226));
        tfAdd.setColumns(20);
        tfAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfAdd.setRows(5);
        tfAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));
        jScrollPane1.setViewportView(tfAdd);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setText("Full Name :");

        tfName.setBackground(new java.awt.Color(226, 226, 226));
        tfName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        btnSaChang.setBackground(new java.awt.Color(24, 17, 68));
        btnSaChang.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSaChang.setForeground(new java.awt.Color(255, 255, 255));
        btnSaChang.setText("Save Changes");
        btnSaChang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaChangActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setText("UserName :");

        tfUName.setBackground(new java.awt.Color(226, 226, 226));
        tfUName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        btnEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_edit_35px.png"))); // NOI18N
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnEdit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_edit_35px.png"))); // NOI18N
        btnEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit2ActionPerformed(evt);
            }
        });

        btnEdit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_edit_35px.png"))); // NOI18N
        btnEdit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit3ActionPerformed(evt);
            }
        });

        btnEdit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_edit_35px.png"))); // NOI18N
        btnEdit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAccDelLayout = new javax.swing.GroupLayout(panAccDel);
        panAccDel.setLayout(panAccDelLayout);
        panAccDelLayout.setHorizontalGroup(
            panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panAccDelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAccDelLayout.createSequentialGroup()
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAccDelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSaChang))
                            .addGroup(panAccDelLayout.createSequentialGroup()
                                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel19))
                                .addGap(80, 80, 80)
                                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfMobNo)
                                    .addComponent(tfEmailId)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(tfName)
                                    .addComponent(tfUName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sbAccDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panAccDelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())))
        );
        panAccDelLayout.setVerticalGroup(
            panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccDelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAccDelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sbAccDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panAccDelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit1))
                        .addGap(31, 31, 31)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(btnSaChang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        mainPan.add(panAccDel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headPan, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
                    .addComponent(mainPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
       setVisible(false);
       new LoginPage().setVisible(true);
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnAccDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccDelMouseClicked
        mSubPan3.setBackground(SecCol);
        mSubPan1.setBackground(DeSecCol);
        panAccDel.setVisible(true);
        panDash.setVisible(false);
        
        try{
            Statement s = c.connect.createStatement();
            ResultSet rs = s.executeQuery("select * from signupNor where userid = '"+userid+"'");
            
            while(rs.next()){
                tfUName.setText(VuserName);
                tfUName.setEditable(false);
                tfMobNo.setText(rs.getString("MobileNo"));
                tfMobNo.setEditable(false);
                tfEmailId.setText(rs.getString("emailid"));
                tfEmailId.setEditable(false);
                tfName.setText(rs.getString("name"));
                tfName.setEditable(false);
                tfAdd.setText(dm.reAdd(rs.getString("ResAdd"), rs.getString("streetN"), rs.getString("area"), rs.getString("landmark"), rs.getString("city"), rs.getString("pincode"), rs.getString("state")));
                tfAdd.setEditable(false);
                
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAccDelMouseClicked

    private void btnDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashMouseClicked
       mSubPan1.setBackground(SecCol);
       mSubPan3.setBackground(DeSecCol);
       
       panDash.setVisible(true);
       panAccDel.setVisible(false);
       
       Dash1.setVisible(true);
       Dash2.setVisible(false);
       
    }//GEN-LAST:event_btnDashMouseClicked

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        tfUName.setEditable(true);
        tfUName.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        Dash2.setVisible(true);
        Dash1.setVisible(false);
        String needTy = tfSearch.getText();
        DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
        mod.setRowCount(0);
  
        if(needTy.equals("Plumber")||needTy.equals("Electrician")||needTy.equals("Barber")||needTy.equals("Carpenter")||needTy.equals("Nurse")||needTy.equals("House Cleaner")||needTy.equals("Car Cleaner")||needTy.equals("Spa")||needTy.equals("Technician")||needTy.equals("Painter")){
            try {
                Statement s = c.connect.createStatement();
                String sql = "select * from signupVen where proff = '"+needTy+"";
            
                ResultSet rs = s.executeQuery(sql);
                while(rs.next()){
                    String vname = rs.getString("name");
                    String vmob = rs.getString("MobileNo");
                    String varea = rs.getString("city");
                    String vyoe = rs.getString("yoe");
                
                    String venData[] = {vname,varea,vyoe,vmob};
                
                    mod.addRow(venData);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
       }else{
            JOptionPane.showMessageDialog(null, "No Such Service Provided");
            Dash1.setVisible(true);
            Dash2.setVisible(false);
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    private void tfSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Dash2.setVisible(true);
            Dash1.setVisible(false);
            String needTy = tfSearch.getText();
            DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
            mod.setRowCount(0);
  
            if(needTy.equals("Plumber")||needTy.equals("Electrician")||needTy.equals("Barber")||needTy.equals("Carpenter")||needTy.equals("Nurse")||needTy.equals("House Cleaner")||needTy.equals("Car Cleaner")||needTy.equals("Spa")||needTy.equals("Technician")||needTy.equals("Painter")){
                try {
                    Statement s = c.connect.createStatement();
                    String sql = "select * from signupVen where proff = '"+needTy+"'";
            
                    ResultSet rs = s.executeQuery(sql);
                    while(rs.next()){
                    String vname = rs.getString("name");
                    String vmob = rs.getString("MobileNo");
                    String varea = rs.getString("city");
                    String vyoe = rs.getString("yoe");
                
                    String venData[] = {vname,varea,vyoe,vmob};
                
                    mod.addRow(venData);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
       }else{
            JOptionPane.showMessageDialog(null, "No Such Service Provided");
            Dash1.setVisible(true);
            Dash2.setVisible(false);
        }
        }
    }//GEN-LAST:event_tfSearchKeyPressed

    private void btnFindPlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPlumActionPerformed
        Dash2.setVisible(true);
        Dash1.setVisible(false);
        
        DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
        mod.setRowCount(0);
        
        String needTy = "Plumber";
        try {
            Statement s = c.connect.createStatement();
            String sql = "select * from signupVen where proff = '"+needTy+"'";
            
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()){
                String vname = rs.getString("name");
                String vmob = rs.getString("MobileNo");
                String varea = rs.getString("city");
                String vyoe = rs.getString("yoe");
                
                String venData[] = {vname,varea,vyoe,vmob};
                
                mod.addRow(venData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFindPlumActionPerformed

    private void btnFindElecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindElecActionPerformed
        Dash2.setVisible(true);
        Dash1.setVisible(false);
        
        DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
        mod.setRowCount(0);
        
        String needTy = "Electrician";
        try {
            Statement s = c.connect.createStatement();
            String sql = "select * from signupVen where proff = '"+needTy+"'";
            
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()){
                String vname = rs.getString("name");
                String vmob = rs.getString("MobileNo");
                String varea = rs.getString("city");
                String vyoe = rs.getString("yoe");
                
                String venData[] = {vname,varea,vyoe,vmob};
                
                mod.addRow(venData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFindElecActionPerformed

    private void btnFindPaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPaintActionPerformed
        Dash2.setVisible(true);
        Dash1.setVisible(false);
        
        DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
        mod.setRowCount(0);
        
        String needTy = "Painter";
        try {
            Statement s = c.connect.createStatement();
            String sql = "select * from signupVen where proff = '"+needTy+"'";
            
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()){
                String vname = rs.getString("name");
                String vmob = rs.getString("MobileNo");
                String varea = rs.getString("city");
                String vyoe = rs.getString("yoe");
                
                String venData[] = {vname,varea,vyoe,vmob};
                
                mod.addRow(venData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFindPaintActionPerformed

    private void btnFindCarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCarpActionPerformed
        Dash2.setVisible(true);
        Dash1.setVisible(false);
        
        DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
        mod.setRowCount(0);
        
        String needTy = "Carpenter";
        try {
            Statement s = c.connect.createStatement();
            String sql = "select * from signupVen where proff = '"+needTy+"'";
            
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()){
                String vname = rs.getString("name");
                String vmob = rs.getString("MobileNo");
                String varea = rs.getString("city");
                String vyoe = rs.getString("yoe");
                
                String venData[] = {vname,varea,vyoe,vmob};
                
                mod.addRow(venData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFindCarpActionPerformed

    private void btnFindTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindTechActionPerformed
        Dash2.setVisible(true);
        Dash1.setVisible(false);
        
        DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
        mod.setRowCount(0);
        
        String needTy = "Technician";
        try {
            Statement s = c.connect.createStatement();
            String sql = "select * from signupVen where proff = '"+needTy+"'";
            
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()){
                String vname = rs.getString("name");
                String vmob = rs.getString("MobileNo");
                String varea = rs.getString("city");
                String vyoe = rs.getString("yoe");
                
                String venData[] = {vname,varea,vyoe,vmob};
                
                mod.addRow(venData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFindTechActionPerformed

    private void btnFindBarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindBarbActionPerformed
        Dash2.setVisible(true);
        Dash1.setVisible(false);
        
        DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
        mod.setRowCount(0);
        
        String needTy = "Barber";
        try {
            Statement s = c.connect.createStatement();
            String sql = "select * from signupVen where proff = '"+needTy+"'";
            
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()){
                String vname = rs.getString("name");
                String vmob = rs.getString("MobileNo");
                String varea = rs.getString("city");
                String vyoe = rs.getString("yoe");
                
                String venData[] = {vname,varea,vyoe,vmob};
                
                mod.addRow(venData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFindBarbActionPerformed

    private void btnFindHCleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindHCleActionPerformed
        Dash2.setVisible(true);
        Dash1.setVisible(false);
        
        DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
        mod.setRowCount(0);
        
        String needTy = "House Cleaner";
        try {
            Statement s = c.connect.createStatement();
            String sql = "select * from signupVen where proff = '"+needTy+"'";
            
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()){
                String vname = rs.getString("name");
                String vmob = rs.getString("MobileNo");
                String varea = rs.getString("city");
                String vyoe = rs.getString("yoe");
                
                String venData[] = {vname,varea,vyoe,vmob};
                
                mod.addRow(venData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFindHCleActionPerformed

    private void btnFindCarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCarClActionPerformed
        Dash2.setVisible(true);
        Dash1.setVisible(false);
        
        DefaultTableModel mod = (DefaultTableModel)venTable.getModel();
        mod.setRowCount(0);
        
        String needTy = "Car Cleaner";
        try {
            PreparedStatement ps = c.connect.prepareStatement("select * from signupVen where proff = ?");
            ps.setString(1,needTy);
            //ps.setString(2, nCity);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                String vname = rs.getString("name");
                String vmob = rs.getString("MobileNo");
                String varea = rs.getString("city");
                String vyoe = rs.getString("yoe");

                String venData[] = {vname,varea,vyoe,vmob};
                
                mod.addRow(venData);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFindCarClActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tfSearch.requestFocusInWindow();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void venTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venTableMouseClicked
        if(evt.getClickCount() ==2){
            int index = venTable.getSelectedRow();
            TableModel model = venTable.getModel();
        
            String venMobNo = model.getValueAt(index,3).toString();
            try {
                Statement s = c.connect.createStatement();
                String sq = "select * from signupVen where MobileNo = '"+venMobNo+"'";
                
                ResultSet rs2 = s.executeQuery(sq);
                while(rs2.next()){
                    String venUserid = rs2.getString("userid");
                    
                    new venDetailsPage(venUserid).setVisible(true);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_venTableMouseClicked

    private void btnrRefRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrRefRMouseClicked
        Dash1.setVisible(true);
        Dash2.setVisible(false);
        
        tfSearch.requestFocusInWindow();
        tfSearch.setText("");
    }//GEN-LAST:event_btnrRefRMouseClicked

    private void btnSaChangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaChangActionPerformed
       String newUserName,newMobNo,newEmaili,newResAdd;
       
       newUserName = tfUName.getText();
       newMobNo = tfMobNo.getText();
       newEmaili= tfEmailId.getText();
       newResAdd = tfAdd.getText();
       
        try {
            PreparedStatement psu = c.connect.prepareStatement("update signupNor set emailid = ? ,MobileNo = ?, where userid = ?");
            psu.setString(1,newEmaili);
            psu.setString(2, newMobNo);
           // psu.setString(3, newResAdd);
            psu.setString(3, userid);
            
            PreparedStatement psu2 = c.connect.prepareStatement("update login set username = ? ,Emailid = ? where userid = ?");
            psu2.setString(1, newUserName);
            psu2.setString(2, newEmaili);
            psu2.setString(3, userid);
            
            int stat1 = psu.executeUpdate();
            int stat2 = psu2.executeUpdate();
            
            if(stat1 == 0 || stat2 == 0){
                JOptionPane.showMessageDialog(null, "Something went Wrong");
            }
            else{
                JOptionPane.showMessageDialog(null, "Changes Saved Successfully");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaChangActionPerformed

    private void btnEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit2ActionPerformed
        tfEmailId.setEditable(true);
        tfEmailId.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnEdit2ActionPerformed

    private void btnEdit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit3ActionPerformed
        tfMobNo.setEditable(true);
        tfMobNo.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnEdit3ActionPerformed

    private void btnEdit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit4ActionPerformed
        tfAdd.setEditable(true);
        tfAdd.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnEdit4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appMain("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dash1;
    private javax.swing.JPanel Dash2;
    private javax.swing.JPanel PanPlumber;
    private javax.swing.JLabel btnAccDel;
    private javax.swing.JLabel btnDash;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnEdit2;
    private javax.swing.JButton btnEdit3;
    private javax.swing.JButton btnEdit4;
    private javax.swing.JButton btnFindBarb;
    private javax.swing.JButton btnFindCarCl;
    private javax.swing.JButton btnFindCarp;
    private javax.swing.JButton btnFindElec;
    private javax.swing.JButton btnFindHCle;
    private javax.swing.JButton btnFindPaint;
    private javax.swing.JButton btnFindPlum;
    private javax.swing.JButton btnFindTech;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JButton btnSaChang;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnrRefR;
    public javax.swing.JPanel hSubPan1;
    public javax.swing.JPanel headPan;
    public javax.swing.JLabel imgLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lBarber;
    private javax.swing.JLabel lCarWashing;
    private javax.swing.JLabel lCarpenter;
    private javax.swing.JLabel lElect;
    private javax.swing.JLabel lHClean;
    private javax.swing.JLabel lPainter;
    private javax.swing.JLabel lPlumber;
    private javax.swing.JLabel lTechni;
    public javax.swing.JLabel lUserName;
    private javax.swing.JPanel mSubPan1;
    private javax.swing.JPanel mSubPan3;
    private javax.swing.JPanel mainPan;
    private javax.swing.JPanel menuPan;
    private javax.swing.JPanel notiPanM;
    private javax.swing.JPanel panAccDel;
    private javax.swing.JPanel panDash;
    private javax.swing.JDialog panNoti;
    private javax.swing.JScrollBar sbAccDel;
    private javax.swing.JTextArea tfAdd;
    private javax.swing.JTextField tfEmailId;
    private javax.swing.JTextField tfMobNo;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfUName;
    private javax.swing.JTable venTable;
    // End of variables declaration//GEN-END:variables
}
