package DUJS.main;

import DUJS.methods.DataMethods;
import DUJS.methods.ImageMethods;
import DUJS.methods.conn;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

public class appMainVen extends javax.swing.JFrame {
        String VuserName,userid,orderid;
        String type = "Vendor";
        String orFrom,orTime,orBudget,orDate,orFor,orStatus,orTitle;
        int Srno = 0;
        Color SecCol = new Color(39,57,81);
        Color DeSecCol = new Color(24,17,68);
        DataMethods dm = new DataMethods();
        conn c = new conn();
        ImageMethods im = new ImageMethods();
    public appMainVen(String userid) {
        initComponents();
        this.lNoOrd.setVisible(false);
        try{
           this.userid = userid;
            
            Statement s = c.connect.createStatement();
            String sql = "select * from login where userid = '"+userid+"'";
            ResultSet rs = s.executeQuery(sql);
            
            while(rs.next()){
                 VuserName = rs.getString("username");
                 lUserName.setText(VuserName);
                 imgLabel.setIcon(im.getImage(imgLabel, userid));
                 hSubPan1.revalidate();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        lGuideLines.setIcon(im.reSize("src/DUJS/Images/guideLines.jpg",lGuideLines));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNoti = new javax.swing.JDialog();
        notiPanM = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        menuPan = new javax.swing.JPanel();
        mSubPan1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnDash = new javax.swing.JLabel();
        mSubPan2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPanOrd = new javax.swing.JLabel();
        mSubPan3 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAccDel = new javax.swing.JLabel();
        headPan = new javax.swing.JPanel();
        hSubPan1 = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lUserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        mainPan = new javax.swing.JPanel();
        panDash = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lGuideLines = new javax.swing.JLabel();
        panOrders = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbOrder = new javax.swing.JTable();
        btnAddOrd = new javax.swing.JButton();
        lNoOrd = new javax.swing.JLabel();
        panAccDel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sbAccDel = new javax.swing.JScrollBar();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfOrgName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfProff = new javax.swing.JTextField();
        tfMobNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfEmailId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAdd = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfAdhaar = new javax.swing.JTextField();
        btnSaChang = new javax.swing.JButton();
        btnEdit3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        tfUName = new javax.swing.JTextField();
        btnEdit1 = new javax.swing.JButton();
        btnEdit2 = new javax.swing.JButton();
        btnEdit4 = new javax.swing.JButton();
        btnEdit5 = new javax.swing.JButton();

        panNoti.setBackground(new java.awt.Color(255, 255, 255));
        panNoti.setUndecorated(true);
        panNoti.setResizable(false);

        notiPanM.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout notiPanMLayout = new javax.swing.GroupLayout(notiPanM);
        notiPanM.setLayout(notiPanMLayout);
        notiPanMLayout.setHorizontalGroup(
            notiPanMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        notiPanMLayout.setVerticalGroup(
            notiPanMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panNotiLayout = new javax.swing.GroupLayout(panNoti.getContentPane());
        panNoti.getContentPane().setLayout(panNotiLayout);
        panNotiLayout.setHorizontalGroup(
            panNotiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notiPanM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panNotiLayout.setVerticalGroup(
            panNotiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notiPanM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        menuPan.setBackground(new java.awt.Color(24, 17, 68));

        mSubPan1.setBackground(new java.awt.Color(39, 57, 81));
        mSubPan1.setPreferredSize(new java.awt.Dimension(149, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        btnDash.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDash.setForeground(new java.awt.Color(255, 255, 255));
        btnDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDash.setText("Dashboard");
        btnDash.setPreferredSize(new java.awt.Dimension(41, 20));
        btnDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mSubPan1Layout = new javax.swing.GroupLayout(mSubPan1);
        mSubPan1.setLayout(mSubPan1Layout);
        mSubPan1Layout.setHorizontalGroup(
            mSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mSubPan1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        mSubPan1Layout.setVerticalGroup(
            mSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mSubPan1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mSubPan2.setBackground(new java.awt.Color(24, 17, 68));
        mSubPan2.setPreferredSize(new java.awt.Dimension(0, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        btnPanOrd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnPanOrd.setForeground(new java.awt.Color(255, 255, 255));
        btnPanOrd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPanOrd.setText("Orders");
        btnPanOrd.setPreferredSize(new java.awt.Dimension(41, 20));
        btnPanOrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanOrdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mSubPan2Layout = new javax.swing.GroupLayout(mSubPan2);
        mSubPan2.setLayout(mSubPan2Layout);
        mSubPan2Layout.setHorizontalGroup(
            mSubPan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mSubPan2Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPanOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        mSubPan2Layout.setVerticalGroup(
            mSubPan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mSubPan2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnPanOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mSubPan3.setBackground(new java.awt.Color(24, 17, 68));
        mSubPan3.setPreferredSize(new java.awt.Dimension(0, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        btnAccDel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnAccDel.setForeground(new java.awt.Color(255, 255, 255));
        btnAccDel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAccDel.setText("Account Details");
        btnAccDel.setPreferredSize(new java.awt.Dimension(41, 20));
        btnAccDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAccDelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mSubPan3Layout = new javax.swing.GroupLayout(mSubPan3);
        mSubPan3.setLayout(mSubPan3Layout);
        mSubPan3Layout.setHorizontalGroup(
            mSubPan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mSubPan3Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mSubPan3Layout.setVerticalGroup(
            mSubPan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mSubPan3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAccDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout menuPanLayout = new javax.swing.GroupLayout(menuPan);
        menuPan.setLayout(menuPanLayout);
        menuPanLayout.setHorizontalGroup(
            menuPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mSubPan1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(mSubPan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(mSubPan3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        menuPanLayout.setVerticalGroup(
            menuPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(mSubPan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mSubPan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mSubPan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headPan.setBackground(new java.awt.Color(204, 255, 255));
        headPan.setPreferredSize(new java.awt.Dimension(1210, 80));

        hSubPan1.setBackground(new java.awt.Color(255, 255, 255));

        imgLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Name :");

        lUserName.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>|<br>|<br>|<br>|<br></html>");

        javax.swing.GroupLayout hSubPan1Layout = new javax.swing.GroupLayout(hSubPan1);
        hSubPan1.setLayout(hSubPan1Layout);
        hSubPan1Layout.setHorizontalGroup(
            hSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hSubPan1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(hSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        hSubPan1Layout.setVerticalGroup(
            hSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hSubPan1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(hSubPan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hSubPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hSubPan1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_Logout_41px.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headPanLayout = new javax.swing.GroupLayout(headPan);
        headPan.setLayout(headPanLayout);
        headPanLayout.setHorizontalGroup(
            headPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headPanLayout.createSequentialGroup()
                .addComponent(btnLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hSubPan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headPanLayout.setVerticalGroup(
            headPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hSubPan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headPanLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPan.setLayout(new java.awt.CardLayout());

        panDash.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel20.setText("Dashboard");

        jLabel21.setText("________________________________________________________________________________________________________________________________________________________________________");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("<html>We Support the Covid-19 Prevention Drive,And Expect you to Maintain the Integrity</html>");

        javax.swing.GroupLayout panDashLayout = new javax.swing.GroupLayout(panDash);
        panDash.setLayout(panDashLayout);
        panDashLayout.setHorizontalGroup(
            panDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panDashLayout.createSequentialGroup()
                .addGroup(panDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDashLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel20))
                    .addGroup(panDashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDashLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lGuideLines, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDashLayout.setVerticalGroup(
            panDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDashLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lGuideLines, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPan.add(panDash, "card2");

        panOrders.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setText("Orders");

        jLabel22.setText("________________________________________________________________________________________________________________________________________________________________________");

        tbOrder.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tbOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "OrderId", "From", "Order", "Date", "Budget", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbOrder.setRowHeight(30);
        tbOrder.getTableHeader().setResizingAllowed(false);
        tbOrder.getTableHeader().setReorderingAllowed(false);
        tbOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbOrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbOrder);
        if (tbOrder.getColumnModel().getColumnCount() > 0) {
            tbOrder.getColumnModel().getColumn(0).setResizable(false);
            tbOrder.getColumnModel().getColumn(1).setResizable(false);
            tbOrder.getColumnModel().getColumn(2).setResizable(false);
            tbOrder.getColumnModel().getColumn(3).setResizable(false);
            tbOrder.getColumnModel().getColumn(4).setResizable(false);
            tbOrder.getColumnModel().getColumn(5).setResizable(false);
            tbOrder.getColumnModel().getColumn(6).setResizable(false);
        }

        btnAddOrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_add_50px.png"))); // NOI18N
        btnAddOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrdActionPerformed(evt);
            }
        });

        lNoOrd.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lNoOrd.setText("No Order History");

        javax.swing.GroupLayout panOrdersLayout = new javax.swing.GroupLayout(panOrders);
        panOrders.setLayout(panOrdersLayout);
        panOrdersLayout.setHorizontalGroup(
            panOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOrdersLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9))
            .addComponent(jLabel22)
            .addGroup(panOrdersLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOrdersLayout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(lNoOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panOrdersLayout.createSequentialGroup()
                .addGap(1093, 1093, 1093)
                .addComponent(btnAddOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panOrdersLayout.setVerticalGroup(
            panOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOrdersLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel22)
                .addGap(7, 7, 7)
                .addGroup(panOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOrdersLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lNoOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAddOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPan.add(panOrders, "card6");

        panAccDel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Account Details :");

        jLabel5.setText("________________________________________________________________________________________________________________________________________________________________________");

        sbAccDel.setBackground(new java.awt.Color(51, 51, 255));
        sbAccDel.setForeground(new java.awt.Color(255, 0, 153));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Organization Name :");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("Profession :");

        tfOrgName.setBackground(new java.awt.Color(226, 226, 226));
        tfOrgName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfOrgName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setText("Mobile No. :");

        tfProff.setBackground(new java.awt.Color(226, 226, 226));
        tfProff.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfProff.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        tfMobNo.setBackground(new java.awt.Color(226, 226, 226));
        tfMobNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfMobNo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("Email Id :");

        tfEmailId.setBackground(new java.awt.Color(226, 226, 226));
        tfEmailId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfEmailId.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setText("Organization Address :");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tfAdd.setBackground(new java.awt.Color(226, 226, 226));
        tfAdd.setColumns(20);
        tfAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfAdd.setRows(5);
        tfAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));
        jScrollPane1.setViewportView(tfAdd);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setText("Full Name :");

        tfName.setBackground(new java.awt.Color(226, 226, 226));
        tfName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setText("Adhaar Number :");

        tfAdhaar.setBackground(new java.awt.Color(226, 226, 226));
        tfAdhaar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfAdhaar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        btnSaChang.setBackground(new java.awt.Color(24, 17, 68));
        btnSaChang.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSaChang.setForeground(new java.awt.Color(255, 255, 255));
        btnSaChang.setText("Save Changes");
        btnSaChang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaChangActionPerformed(evt);
            }
        });

        btnEdit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_edit_35px.png"))); // NOI18N
        btnEdit3.setBorder(null);
        btnEdit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setText("UserName :");

        tfUName.setBackground(new java.awt.Color(226, 226, 226));
        tfUName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(24, 17, 68)));

        btnEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_edit_35px.png"))); // NOI18N
        btnEdit1.setBorder(null);
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnEdit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_edit_35px.png"))); // NOI18N
        btnEdit2.setBorder(null);
        btnEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit2ActionPerformed(evt);
            }
        });

        btnEdit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_edit_35px.png"))); // NOI18N
        btnEdit4.setBorder(null);
        btnEdit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit4ActionPerformed(evt);
            }
        });

        btnEdit5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DUJS/Images/icons8_edit_35px.png"))); // NOI18N
        btnEdit5.setBorder(null);
        btnEdit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAccDelLayout = new javax.swing.GroupLayout(panAccDel);
        panAccDel.setLayout(panAccDelLayout);
        panAccDelLayout.setHorizontalGroup(
            panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panAccDelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAccDelLayout.createSequentialGroup()
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAccDelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSaChang))
                            .addGroup(panAccDelLayout.createSequentialGroup()
                                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel19))
                                .addGap(68, 68, 68)
                                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfOrgName)
                                    .addComponent(tfProff)
                                    .addComponent(tfMobNo)
                                    .addComponent(tfEmailId)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(tfName)
                                    .addComponent(tfAdhaar)
                                    .addComponent(tfUName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sbAccDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panAccDelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())))
        );
        panAccDelLayout.setVerticalGroup(
            panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccDelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAccDelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(tfOrgName))
                        .addGap(18, 18, 18)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfProff, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(tfMobNo))
                        .addGap(18, 18, 18)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(tfEmailId))
                        .addGap(18, 18, 18)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(tfAdhaar))
                        .addGap(18, 18, 18)
                        .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panAccDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addComponent(tfUName))
                            .addComponent(btnEdit5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSaChang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAccDelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sbAccDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        mainPan.add(panAccDel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headPan, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
                    .addComponent(mainPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPan, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
       setVisible(false);
       new LoginPage().setVisible(true);
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnAccDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccDelMouseClicked
        mSubPan3.setBackground(SecCol);
        mSubPan1.setBackground(DeSecCol);
        mSubPan2.setBackground(DeSecCol);

        panAccDel.setVisible(true);
        panDash.setVisible(false);
        panOrders.setVisible(false);
        
        try{
            Statement s = c.connect.createStatement();
            ResultSet rs = s.executeQuery("select * from signupVen where userid = '"+userid+"' ");
            
            while(rs.next()){
                tfUName.setText(VuserName);
                tfUName.setEditable(false);
                tfOrgName.setText(rs.getString("orgN"));
                tfOrgName.setEditable(false);
                tfProff.setText(rs.getString("proff"));
                tfProff.setEditable(false);
                tfMobNo.setText(rs.getString("MobileNo"));
                tfMobNo.setEditable(false);
                tfEmailId.setText(rs.getString("emailid"));
                tfEmailId.setEditable(false);
                tfName.setText(rs.getString("name"));
                tfName.setEditable(false);
                tfAdhaar.setText(rs.getString("adhaar"));
                tfAdhaar.setEditable(false);
                tfAdd.setText(dm.reAdd(rs.getString("ResAdd"), rs.getString("streetN"), rs.getString("area"), rs.getString("landmark"), rs.getString("city"), rs.getString("pincode"), rs.getString("state")));
                tfAdd.setEditable(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAccDelMouseClicked

    private void btnDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashMouseClicked
       mSubPan1.setBackground(SecCol);
       mSubPan2.setBackground(DeSecCol);
       mSubPan3.setBackground(DeSecCol);
       
       panDash.setVisible(true);
       panOrders.setVisible(false);
       panAccDel.setVisible(false);
       
    }//GEN-LAST:event_btnDashMouseClicked

    private void btnAddOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrdActionPerformed
        new frOrder(userid).setVisible(true);
    }//GEN-LAST:event_btnAddOrdActionPerformed

    private void btnPanOrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanOrdMouseClicked
       mSubPan1.setBackground(DeSecCol);
       mSubPan2.setBackground(SecCol);
       mSubPan3.setBackground(DeSecCol);
       DefaultTableModel mod = (DefaultTableModel)tbOrder.getModel();
       mod.setRowCount(0);
       Srno = 0;
       panOrders.setVisible(true);
       panDash.setVisible(false);
       panAccDel.setVisible(false);
       
        try {
            Statement s = c.connect.createStatement();
            String sql = "select * from venOrder where venUserid = '"+userid+"'";
            
            ResultSet rs = s.executeQuery(sql);
            
            while(rs.next()){
                Srno = Srno + 1;
                orderid = rs.getString("OrderId");
                orFrom = rs.getString("orFrom");
                orDate = rs.getString("orDate");
                orBudget = rs.getString("orBudget");
                orTitle = rs.getString("OrdTitle");
                orStatus = rs.getString("orStatus");
                
                String venOrData[] = {(Integer.toString(Srno)),orderid,orFrom,orTitle,orDate,orBudget,orStatus};
                
                mod.addRow(venOrData);
            }
        } catch (Exception Ignorred) {
            lNoOrd.setVisible(true);
            tbOrder.setVisible(false);
            panOrders.repaint(); 
        }
    }//GEN-LAST:event_btnPanOrdMouseClicked

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        tfOrgName.setBackground(Color.WHITE);
        tfOrgName.setEditable(true);
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit2ActionPerformed
        tfMobNo.setBackground(Color.WHITE);
        tfMobNo.setEditable(true);
    }//GEN-LAST:event_btnEdit2ActionPerformed

    private void btnEdit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit3ActionPerformed
       tfEmailId.setBackground(Color.WHITE);
       tfEmailId.setEditable(true);
    }//GEN-LAST:event_btnEdit3ActionPerformed

    private void btnEdit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit4ActionPerformed
        tfAdd.setBackground(Color.WHITE);
        tfAdd.setEditable(true);
    }//GEN-LAST:event_btnEdit4ActionPerformed

    private void btnEdit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit5ActionPerformed
        tfUName.setBackground(Color.WHITE);
        tfUName.setEditable(true);
    }//GEN-LAST:event_btnEdit5ActionPerformed

    private void btnSaChangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaChangActionPerformed
        String nUserName,nOrgName,nMobNo,nEmailid,nOrgAdd;
        
        nUserName = tfUName.getText();
        nOrgName = tfOrgName.getText();
        nMobNo = tfMobNo.getText();
        nEmailid = tfEmailId.getText();
        nOrgAdd = tfAdd.getText();
        
        try {
            PreparedStatement psu = c.connect.prepareStatement("update signupVen set emailid = ?, MobileNo = ?,orgN = ? where userid = ?");
            psu.setString(1, nEmailid);
            psu.setString(2, nMobNo);
           // psu.setString(3, nOrgAdd);
            psu.setString(3, nOrgName);
            psu.setString(4, userid);
            
            PreparedStatement psu2 = c.connect.prepareStatement("update login set username = ?,Emailid = ? where userid = ?");
            psu2.setString(1, nUserName);
            psu2.setString(2, nEmailid);
            psu2.setString(3, userid);
            
            int stat1 = psu.executeUpdate();
            int stat2 = psu2.executeUpdate();
            
            if(stat1 == 0 || stat2 == 0){
                JOptionPane.showMessageDialog(null, "Something Went Wrong");
            }else{
                JOptionPane.showMessageDialog(null, "Changes Saved Successfully");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaChangActionPerformed

    private void tbOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbOrderMouseClicked
        if(evt.getClickCount() == 2){
            int index = tbOrder.getSelectedRow();
            TableModel model = tbOrder.getModel();
            
            String sOrderId = model.getValueAt(index, 1).toString();
            new venOrderFr(sOrderId).setVisible(true);
        }
    }//GEN-LAST:event_tbOrderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appMainVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appMainVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appMainVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appMainVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appMainVen("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAccDel;
    private javax.swing.JButton btnAddOrd;
    private javax.swing.JLabel btnDash;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnEdit2;
    private javax.swing.JButton btnEdit3;
    private javax.swing.JButton btnEdit4;
    private javax.swing.JButton btnEdit5;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JLabel btnPanOrd;
    private javax.swing.JButton btnSaChang;
    public javax.swing.JPanel hSubPan1;
    public javax.swing.JPanel headPan;
    public javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lGuideLines;
    private javax.swing.JLabel lNoOrd;
    public javax.swing.JLabel lUserName;
    private javax.swing.JPanel mSubPan1;
    private javax.swing.JPanel mSubPan2;
    private javax.swing.JPanel mSubPan3;
    private javax.swing.JPanel mainPan;
    private javax.swing.JPanel menuPan;
    private javax.swing.JPanel notiPanM;
    private javax.swing.JPanel panAccDel;
    private javax.swing.JPanel panDash;
    private javax.swing.JDialog panNoti;
    private javax.swing.JPanel panOrders;
    private javax.swing.JScrollBar sbAccDel;
    private javax.swing.JTable tbOrder;
    private javax.swing.JTextArea tfAdd;
    private javax.swing.JTextField tfAdhaar;
    private javax.swing.JTextField tfEmailId;
    private javax.swing.JTextField tfMobNo;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfOrgName;
    private javax.swing.JTextField tfProff;
    private javax.swing.JTextField tfUName;
    // End of variables declaration//GEN-END:variables
}
