package DUJS.design;

import DUJS.methods.SendMail;
import DUJS.methods.conn;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;


public class PassForg extends javax.swing.JFrame {
   String gotp,otp;
   String Emto;
   String username;
   String Emcon ;
   String Emsub;
   String nPass,rPass;
   
   conn c = new conn();
    public PassForg() {
       
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailSec = new javax.swing.JPanel();
        SendOTP = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        ConOTP = new javax.swing.JPanel();
        btnConOTP = new javax.swing.JButton();
        btnResOTP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfOTP = new javax.swing.JTextField();
        btnBack2 = new javax.swing.JButton();
        NewPass = new javax.swing.JPanel();
        btnPassCh = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        tfNPass = new javax.swing.JTextField();
        tfRPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new java.awt.CardLayout());

        EmailSec.setBackground(new java.awt.Color(255, 255, 255));

        SendOTP.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SendOTP.setText("Send OTP");
        SendOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendOTPActionPerformed(evt);
            }
        });

        btnBack1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Email Id:");

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfEmail.setToolTipText("Email Address");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("UserName :");

        tfUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmailSecLayout = new javax.swing.GroupLayout(EmailSec);
        EmailSec.setLayout(EmailSecLayout);
        EmailSecLayout.setHorizontalGroup(
            EmailSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailSecLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(SendOTP)
                .addGap(74, 74, 74)
                .addComponent(btnBack1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmailSecLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(EmailSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmailSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        EmailSecLayout.setVerticalGroup(
            EmailSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmailSecLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(EmailSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(EmailSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(EmailSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendOTP)
                    .addComponent(btnBack1))
                .addGap(50, 50, 50))
        );

        getContentPane().add(EmailSec, "card2");

        ConOTP.setBackground(new java.awt.Color(255, 255, 255));

        btnConOTP.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnConOTP.setText("Confirm OTP");
        btnConOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConOTPActionPerformed(evt);
            }
        });

        btnResOTP.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnResOTP.setText("Resend OTP");
        btnResOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResOTPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Enter OTP :");

        tfOTP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfOTP.setToolTipText("Enter OTP");

        btnBack2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConOTPLayout = new javax.swing.GroupLayout(ConOTP);
        ConOTP.setLayout(ConOTPLayout);
        ConOTPLayout.setHorizontalGroup(
            ConOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConOTPLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(ConOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConOTPLayout.createSequentialGroup()
                        .addComponent(btnConOTP)
                        .addGap(75, 75, 75)
                        .addComponent(btnResOTP)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConOTPLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConOTPLayout.createSequentialGroup()
                        .addComponent(btnBack2)
                        .addGap(181, 181, 181))))
        );
        ConOTPLayout.setVerticalGroup(
            ConOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConOTPLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(ConOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(ConOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConOTP)
                    .addComponent(btnResOTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(ConOTP, "card3");

        NewPass.setBackground(new java.awt.Color(255, 255, 255));

        btnPassCh.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnPassCh.setText("Change Password");
        btnPassCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassChActionPerformed(evt);
            }
        });

        btnBack3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBack3.setText("Back");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Enter New Password :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Re-Enter New Password :");

        javax.swing.GroupLayout NewPassLayout = new javax.swing.GroupLayout(NewPass);
        NewPass.setLayout(NewPassLayout);
        NewPassLayout.setHorizontalGroup(
            NewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPassCh)
                .addGap(29, 29, 29)
                .addComponent(btnBack3)
                .addGap(85, 85, 85))
            .addGroup(NewPassLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(NewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NewPassLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewPassLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfRPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NewPassLayout.setVerticalGroup(
            NewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPassLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(NewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNPass, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(NewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfRPass, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(NewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPassCh)
                    .addComponent(btnBack3))
                .addGap(44, 44, 44))
        );

        getContentPane().add(NewPass, "card4");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void SendOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendOTPActionPerformed

            Random rmd = new Random();
            long first4 = (rmd.nextLong() % 9000L) + 1000L;
            otp = "" +Math.abs(first4);

            Emto = tfEmail.getText();
            username = tfUserName.getText();

            EmailSec.setVisible(false);
            ConOTP.setVisible(true);

            Emcon = "Dear User "+username+",Your request for Changing Password has been Processed and this One Time Password is generated :\n"+otp+"\nEnter the OTP in the required Field/n/nREGARDS";
            Emsub = "Password Reset";

            SendMail.sendMail(Emto,Emsub,Emcon,otp);
    }//GEN-LAST:event_SendOTPActionPerformed

    private void btnConOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConOTPActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==btnConOTP){
            gotp = tfOTP.getText();
            if(gotp.equals(otp)){
                ConOTP.setVisible(false);
                NewPass.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect OTP,Please Check and Retry");
            }

        }
    }//GEN-LAST:event_btnConOTPActionPerformed

    private void btnResOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResOTPActionPerformed

            SendMail.sendMail(Emto, Emsub, Emcon, gotp);
            JOptionPane.showMessageDialog(null, "One Time Password Resent");
    }//GEN-LAST:event_btnResOTPActionPerformed

    private void btnPassChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassChActionPerformed

            nPass = tfNPass.getText();
            rPass = tfRPass.getText();
            if(nPass.equals(rPass)){
                try {
                    Statement s = c.connect.createStatement();
                    String sql = "update login set password = '"+nPass+"'where username = '"+username+"'";
                    
                    int Status = s.executeUpdate(sql);
                    
                    if(Status == 0){
                        JOptionPane.showMessageDialog(null,"Something went Wrong");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Password changed Succesfully");
                        setVisible(false);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Password do not match");
            }
    }//GEN-LAST:event_btnPassChActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed

            setVisible(false);
    }//GEN-LAST:event_btnBack1ActionPerformed



    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==btnBack3){
            NewPass.setVisible(false);
            ConOTP.setVisible(true);
        }
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==btnBack2){
            ConOTP.setVisible(false);
            EmailSec.setVisible(true);
        }
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void tfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserNameActionPerformed







    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassForg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassForg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassForg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassForg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConOTP;
    private javax.swing.JPanel EmailSec;
    private javax.swing.JPanel NewPass;
    private javax.swing.JButton SendOTP;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnConOTP;
    private javax.swing.JButton btnPassCh;
    private javax.swing.JButton btnResOTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNPass;
    private javax.swing.JTextField tfOTP;
    private javax.swing.JTextField tfRPass;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
}
